### ISSUE TITLE
正常训练后，中途报错求助

### ISSUE THREAD

**Issue by ShangkunTu** [PlayVoice/vits_chinese#109]
作者您好，当我正常训练到35W步的时候，我想尝试一下把32w步这个模型当作教师模型去蒸馏一下，执行
python vits_infer.py --config ./configs/bert_vits_student.json --model vits_bert_student.pth之后报如下错误，然后用普通训练的方式命令去训练也是报如下的错误，但是推理是可以正常推理的，我本来以为可能是我下午改代码的时候把代码改出来了一些问题，所以尝试重新下载了以下您的包，用原来的环境，也是可以正常推理的，但是还是报如下错误，向您请教，感谢！：
WARNING:bert_vits_student:/home/TuSK/Codes/vits_chinese-master is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "/home/TuSK/Codes/vits_chinese-master/train.py", line 442, in <module>
    main()
  File "/home/TuSK/Codes/vits_chinese-master/train.py", line 44, in main
    mp.spawn(
  File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/TuSK/Codes/vits_chinese-master/train.py", line 70, in run
    train_dataset = TextAudioLoader(hps.data.training_files, hps.data)
  File "/home/TuSK/Codes/vits_chinese-master/data_utils.py", line 38, in __init__
    self._filter()
  File "/home/TuSK/Codes/vits_chinese-master/data_utils.py", line 50, in _filter
    for audiopath, spec, bert, text in self.audiopaths_and_text:
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by ShangkunTu** [comment]
> 作者您好，当我正常训练到35W步的时候，我想尝试一下把32w步这个模型当作教师模型去蒸馏一下，执行 python vits_infer.py --config ./configs/bert_vits_student.json --model vits_bert_student.pth之后报如下错误，然后用普通训练的方式命令去训练也是报如下的错误，但是推理是可以正常推理的，我本来以为可能是我下午改代码的时候把代码改出来了一些问题，所以尝试重新下载了以下您的包，用原来的环境，也是可以正常推理的，但是还是报如下错误，向您请教，感谢！： WARNING:bert_vits_student:/home/TuSK/Codes/vits_chinese-master is not a git repository, therefore hash value comparison will be ignored. INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0 INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes. Traceback (most recent call last): File "/home/TuSK/Codes/vits_chinese-master/train.py", line 442, in main() File "/home/TuSK/Codes/vits_chinese-master/train.py", line 44, in main mp.spawn( File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes while not context.join(): File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join raise ProcessRaisedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 0 terminated with the following error: Traceback (most recent call last): File "/home/TuSK/anaconda3/envs/vits_chinese/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap fn(i, *args) File "/home/TuSK/Codes/vits_chinese-master/train.py", line 70, in run train_dataset = TextAudioLoader(hps.data.training_files, hps.data) File "/home/TuSK/Codes/vits_chinese-master/data_utils.py", line 38, in **init** self._filter() File "/home/TuSK/Codes/vits_chinese-master/data_utils.py", line 50, in _filter for audiopath, spec, bert, text in self.audiopaths_and_text: ValueError: not enough values to unpack (expected 4, got 3)

不好意思，抛了个稀奇古怪的问题给您，我最终找到问题了，是我在修改代码的时候，不小心损坏了预处理的生成的文件，导致程序报错，重新运行训练前的预处理文件后，就正常了
