### ISSUE TITLE
onnx 版本问题

### ISSUE THREAD

**Issue by nicken** [PlayVoice/vits_chinese#170]
你好，我在进行onnx转换的时候遇到以下问题, 初步怀疑是版本的问题
可以提供一下onnx 和 onnxruntime的版本么？

```shell
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Traceback (most recent call last):
  File "/home/test/Kingsware/tts/vits_chinese/vits_chinese/model_onnx.py", line 294, in <module>
    main()
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/Kingsware/tts/vits_chinese/vits_chinese/model_onnx.py", line 254, in main
    torch.onnx.export(
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/test/.pyenv/versions/3.9.16/envs/vits/lib/python3.9/site-packages/torch/onnx/symbolic_opset13.py", line 73, in split
    if self.type().sizes()[dim] is not None:
TypeError: 'NoneType' object is not subscriptable 
(Occurred when translating split).
```

**Comment by yegeli** [comment]
hello
"Has this issue been resolved?"

**Comment by yegeli** [comment]
set opset_version = 11
