### ISSUE TITLE
RuntimeError: The expanded size of the tensor (50) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 50].  Tensor sizes: [192, 0]

### ISSUE THREAD

**Issue by showmelater** [PlayVoice/vits_chinese#49]
大佬你好。自定义的数据集，执行完vits_prepare_4_custom_speaker.py后，再执行的train.py  ，错误中显示了维度不一致怎么解决呢？

报错如下：
Traceback (most recent call last):
  File "train.py", line 436, in <module>
    main()
  File "train.py", line 49, in main
    hps,
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/vits_chinese/train.py", line 168, in run
    [writer, writer_eval],
  File "/root/vits_chinese/train.py", line 216, in train_and_evaluate
    (z, z_p, z_r, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, bert, spec, spec_lengths)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/vits_chinese/models.py", line 544, in forward
    z, y_lengths, self.segment_size
  File "/root/vits_chinese/commons.py", line 65, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/root/vits_chinese/commons.py", line 55, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (50) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 50].  Tensor sizes: [192, 0]

**Comment by MaxMax2016** [comment]
把batch size设置为1，看看具体是哪条数据的问题，需要data loader里面加个打印，把文件名打印出来，再看数据标注标注。

**Comment by showmelater** [comment]
能具体讲一下嘛，函数我找了好久，python基础有点差

**Comment by showmelater** [comment]
感谢大佬指导！我在data_utils.py  line58  中添加了
def get_audio_text_pair(self, audiopath_and_text)

**Comment by showmelater** [comment]
醉了，能跑一部分，删一个，又会有新的出现

**Comment by MaxMax2016** [comment]
啊，直接删除的啊，没分析出错误原因？

**Comment by showmelater** [comment]
感觉转换的韵律标注都是对的，有空再看看吧

**Comment by AwakingsWings** [comment]
@showmelater  我看了一下，你这个好像不是文本转音素的问题，是语音的问题。是梅尔频谱的缓存出现了空缓存。
梅尔频谱本身需要有一个加窗的过程，视实现不同（我只看过librosa的，他这个是用torch的，原理应该类似），你的音频文件必须要至少达到1帧长+窗口时长才能有结果，否则就会返回空。
一个简单的建议：在数据清洗时直接干掉所有一秒内的音频，本来短时样本的质量就偏低。

**Comment by showmelater** [comment]
对，样本语音大部分都在1-2s左右，等下我调长点再试试

**Comment by showmelater** [comment]
剔除了短于2s的音频，没任何问题了
