### ISSUE TITLE
您好！请问大佬有没有遇到这种情况？

### ISSUE THREAD

**Issue by 15755841658** [PlayVoice/vits_chinese#7]
您好！请问大佬有没有遇到这种情况？
WARNING:female_base:/qdell3data/qwork/txw94/qdell3/TTS/vits-main is not a git repository, therefore hash value comparison will be ignored.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
/qwork4/twu/miniconda/envs/tts/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 32 leaked semaphores to clean up at shutdown
  len(cache))
/qwork4/twu/miniconda/envs/tts/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 32 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "train.py", line 297, in <module>
    main()
  File "train.py", line 57, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/qdell3data/qwork/txw94/qdell3/TTS/vits-main/train.py", line 126, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, None], None, None)
  File "/qdell3data/qwork/txw94/qdell3/TTS/vits-main/train.py", line 151, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, spec, spec_lengths)
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/qdell3data/qwork/txw94/qdell3/TTS/vits-main/models.py", line 467, in forward
    z, m_q, logs_q, y_mask = self.enc_q(y, y_lengths, g=g)
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/qdell3data/qwork/txw94/qdell3/TTS/vits-main/models.py", line 237, in forward
    x = self.enc(x, x_mask, g=g)
  File "/qwork4/twu/miniconda/envs/tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/qdell3data/qwork/txw94/qdell3/TTS/vits-main/modules.py", line 166, in forward
    n_channels_tensor)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: __nv_nvrtc_builtin_header.h(78048): error: function "operator delete(void *, size_t)" has already been defined

__nv_nvrtc_builtin_header.h(78049): error: function "operator delete[](void *, size_t)" has already been defined

2 errors detected in the compilation of "default_program".

**Comment by dtx525942103** [comment]
你检查一下pytorch个cuda是否兼容，不是随便安装就能用
