### ISSUE TITLE
Train 的vits_prepare.py 运行错误：IndexError: Replacement index 2 out of range for positional args tuple    

### ISSUE THREAD

**Issue by 1040003585** [PlayVoice/vits_chinese#72]
**我按README.md 来操作，如下训练有错误，请问需要怎么处理？**

### Train
download baker data: https://www.data-baker.com/data/index/TNtts/

change sample rate of waves to 16kHz, and put waves to ./data/waves

put 000001-010000.txt to ./data/000001-010000.txt

> python vits_prepare.py -c ./configs/bert_vits.json

### 运行错误：
```
Traceback (most recent call last):                                                                     
File "vits_prepare.py", line 126, in <module>                                                          
spec = get_spec(hps, wave_path)                                                                    
File "vits_prepare.py", line 27, in get_spec                                                           
"{} {} SR doesn't match target {} SR".format(                                                    
IndexError: Replacement index 2 out of range for positional args tuple     
```

**Comment by MaxMax2016** [comment]
采样率不匹配

**Comment by 1040003585** [comment]
用什么工具方便把这些语料库转为格式的采样率？

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/so-vits-svc-5.0/blob/main/prepare/preprocess_a.py

python preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000

**Comment by 1040003585** [comment]
vits_prepare.py  可以运行起来，然后有很多如下错误，需要怎么修改？：
except: list index out of range

**Comment by MaxMax2016** [comment]
是标贝数据集吗？这个错误是儿化音标注导致了，不会处理，不会影响训练，只是模型不支持儿化音。~

**Comment by 1040003585** [comment]
是的，所有带“儿”的语句都有这个提示。感谢回复
