### ISSUE TITLE
RuntimeError: The expanded size of the tensor (50) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 50].  Tensor sizes: [192, 0]

### ISSUE THREAD

**Issue by m1258218761** [PlayVoice/vits_chinese#78]
Traceback (most recent call last):
  File "/root/miniconda3/envs/vits/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data1/Minxin/TTS/vits_chinese/train.py", line 161, in run
    train_and_evaluate(
  File "/data1/Minxin/TTS/vits_chinese/train.py", line 219, in train_and_evaluate
    (z, z_p, z_r, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, bert, spec, spec_lengths)
  File "/root/miniconda3/envs/vits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/vits/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/vits/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/vits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/Minxin/TTS/vits_chinese/models.py", line 543, in forward
    z_slice, ids_slice = commons.rand_slice_segments(
  File "/data1/Minxin/TTS/vits_chinese/commons.py", line 65, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/data1/Minxin/TTS/vits_chinese/commons.py", line 55, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (50) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 50].  Tensor sizes: [192, 0]

请问大佬，我这个是什么问题呀，自己做的数据，音频也按16k采样了，正常跑了几十个batch后就报这个错了

**Comment by MaxMax2016** [comment]
有点像某个音频有问题

**Comment by haiewu** [comment]
音频太短了，需要大于2秒以上

**Comment by xueyuanZ** [comment]
您好，请问这个问题您是怎么解决的？
