### ISSUE TITLE
老师您好，还有一个问题，就是使用标贝数据训练时，如果我把训练数据集减小至7000条以下，就会报这个错，您能帮我分析一下吗？

### ISSUE THREAD

**Issue by liumingda** [PlayVoice/vits_chinese#88]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f659cdc9dc0>
Traceback (most recent call last):
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1268, in _shutdown_workers
    if not self._shutdown:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    main()
  File "train.py", line 43, in main
    mp.spawn(
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/notebook/code/personal/S9052934/vits/tts/vits_chinese-master/train.py", line 159, in run
    train_and_evaluate(
  File "/home/notebook/code/personal/S9052934/vits/tts/vits_chinese-master/train.py", line 203, in train_and_evaluate
    for batch_idx, (x, x_lengths, bert, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 878, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/opt/conda/envs/diffsinger/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 497, in __init__
    self._sampler_iter = iter(self._index_sampler)
  File "/home/notebook/code/personal/S9052934/vits/tts/vits_chinese-master/data_utils.py", line 236, in __iter__
    + ids_bucket * (rem // len_bucket)
ZeroDivisionError: integer division or modulo by zero

**Comment by MaxMax2016** [comment]
![Screenshot_2023-06-10-10-58-12-29_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/PlayVoice/vits_chinese/assets/16432329/ef3d996f-cd19-4778-b1f9-2714ff2818a5) 加个这个？我现在不方便操作

**Comment by liumingda** [comment]
我去试试，谢谢老师！
